%YAML:1.0

#common parameters
savePath: "/home/ron/LaserCameraCal_ws/src/bagfiles/log/"
bag_path: "/home/ron/LaserCameraCal_ws/src/bagfiles/camd435i.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/color/image_raw"

# tag info
tag_type: 2 # 1: kalibr_tag, 2: apriltag
tag_size: 0.088 # tag size, unit meter
tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 1 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1
 
#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720

distortion_parameters:
   k1: 0.16375563343621427
   k2: -0.3102768678407425
   p1: -0.003912176364130468
   p2: 0.00035347945978329463

projection_parameters:
   fx: 611.6619978415015
   fy: 612.3504421750998
   cx: 321.2198443262521
   cy: 231.62284705305117
